/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  basicRulesSidebar: [{type: 'autogenerated', dirName: '01-basic-rules'}],
  adventurerSidebar: [{type: 'autogenerated', dirName: '02-adventurers'}],
  statisticsSidebar: [{type: 'autogenerated', dirName: '03-statistics'}],
  equipmentSidebar: [{type: 'autogenerated', dirName: '04-equipment'}],
  combatSidebar: [{type: 'autogenerated', dirName: '05-combat'}],
  sceneSidebar: [{type: 'autogenerated', dirName: '06-scenes'}],
  magicSidebar: [{type: 'autogenerated', dirName: '07-magic'}],
  creatureSidebar: [{type: 'autogenerated', dirName: '08-creatures'}],
  characterSheetSidebar: [{type: 'autogenerated', dirName: '09-tools'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
