/**
 * Navbar sigil mask generator (M10 S3).
 *
 * The navbar renders a chapter mark as a CSS `mask-image` holding an SVG data
 * URI, so the geometry lives in `custom.css` as well as in `sigil-paths.ts`.
 * That block used to be hand-inlined under a comment claiming it was generated —
 * this script makes the claim true.
 *
 *   bun run sigils:masks           rewrite the block in place
 *   bun run sigils:masks --check   fail if the committed block is stale
 *
 * Which marks get a rule is read from `docusaurus.config.js` (`navbar-sigil--x`),
 * not assumed, so a navbar item pointing at a mark that no longer exists fails
 * the generator instead of silently rendering nothing.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
	SIGIL_INNER,
	SIGIL_VIEWBOX,
	SigilName,
} from '../../components/codex/sigil-paths'

const ROOT = resolve(import.meta.dirname, '../../..')
const CSS_PATH = resolve(ROOT, 'src/css/custom.css')
const CONFIG_PATH = resolve(ROOT, 'docusaurus.config.js')

const START =
	'/* sigils:masks:start — generated by `bun run sigils:masks`, do not edit */'
const END = '/* sigils:masks:end */'

/**
 * Percent-encode only what a `url("…")` data URI cannot carry literally. Keeping
 * `/`, `=` and `'` readable makes the generated block reviewable in a diff.
 */
function encodeSvg(svg: string): string {
	return svg.replace(
		/[<>#%"\s]/g,
		(c) => `%${c.charCodeAt(0).toString(16).toUpperCase().padStart(2, '0')}`,
	)
}

function dataUri(name: SigilName): string {
	const inner = SIGIL_INNER[name]
	const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${SIGIL_VIEWBOX} ${SIGIL_VIEWBOX}' fill='#000'>${inner}</svg>`
	return `data:image/svg+xml,${encodeSvg(svg)}`
}

/** Mark names the navbar actually references, in config order. */
export function navbarSigilNames(configSource: string): SigilName[] {
	const names = [...configSource.matchAll(/navbar-sigil--([a-z-]+)/g)].map(
		(m) => m[1],
	)
	const unique = [...new Set(names)]
	const unknown = unique.filter((n) => !(n in SIGIL_INNER))
	if (unknown.length) {
		throw new Error(
			`docusaurus.config.js references unknown sigils: ${unknown.join(', ')}`,
		)
	}
	return unique as SigilName[]
}

export function renderBlock(names: SigilName[]): string {
	const rules = names.map((name) => {
		const uri = dataUri(name)
		return `  .navbar-sigil--${name}::before { -webkit-mask-image: url("${uri}"); mask-image: url("${uri}"); }`
	})
	return [START, ...rules, END].join('\n')
}

function replaceBlock(css: string, block: string): string {
	const start = css.indexOf(START)
	const end = css.indexOf(END)
	if (start === -1 || end === -1) {
		throw new Error(
			`sigil mask sentinels not found in custom.css — expected ${START} … ${END}`,
		)
	}
	return css.slice(0, start) + block + css.slice(end + END.length)
}

function main() {
	const check = process.argv.includes('--check')
	const css = readFileSync(CSS_PATH, 'utf8')
	const names = navbarSigilNames(readFileSync(CONFIG_PATH, 'utf8'))
	const next = replaceBlock(css, renderBlock(names))

	if (next === css) {
		console.log(`sigils:masks — up to date (${names.length} marks)`)
		return
	}
	if (check) {
		console.error(
			'sigils:masks --check FAILED: the navbar mask block in src/css/custom.css\n' +
				'does not match the geometry in sigil-paths.ts. Run `bun run sigils:masks`.',
		)
		process.exit(1)
	}
	writeFileSync(CSS_PATH, next)
	console.log(`sigils:masks — wrote ${names.length} mask rules to custom.css`)
}

if (import.meta.main) main()
