export const sampleImport = JSON.stringify({
	collectionId: 'bk9fFOilRKeIbHX0Fabgj24OhSZ2',
	skills: {
		xp: {
			spend: 6,
			total: 6,
		},
		skills: [
			{
				id: '45e99f92-db6a-4c3d-abb3-0fe830e4b0e3',
				xp: 2,
				rank: 1,
				name: 'Arcana',
			},
			{
				name: 'Cunning',
				id: '33e3e30a-0b7f-4b25-8d20-d0ebf27b3423',
				xp: 0,
				rank: 0,
			},
			{
				name: 'Education',
				rank: 1,
				xp: 2,
				id: '09213bed-a5dd-49a8-822b-7020fe7bd75c',
			},
			{
				id: '77072111-bfbf-4776-a237-8be6edefdd69',
				rank: 0,
				xp: 0,
				name: 'Lore',
			},
			{
				name: 'Influence',
				xp: 2,
				rank: 1,
				id: '3c54b01c-e6d5-4f65-a9b4-e9524362cff4',
			},
			{
				xp: 0,
				id: '839a1f58-555a-49af-a898-414e5e184180',
				name: 'Insight',
				rank: 0,
			},
			{
				rank: 0,
				id: 'd83357a8-05cb-48ad-8b03-4477324e11e7',
				name: 'Perception',
				xp: 0,
			},
		],
		abilities: [
			{
				id: 'd475d6b1-41e6-46cf-899d-31e0384e4494',
				description:
					'(Rank 1) Learn two rank 0 or 1 spells for any of your disciplines, or adopt a new discipline and learn one new rank 0 spell for it. You can choose this Talent multiple times.',
				title: 'Arcane Spell Knowledge',
			},
			{
				id: '86c65e8f-2313-4951-922e-34d1f922485b',
				description:
					'(Rank 1) You gain the following abilities:\n- You learn one new common or exotic language.\n- You are able to communicate simple ideas with other intelligent, non-hostile creatures you don’t share a language with by rolling Mind + Education (the GM decides on the difficulty of your communication attempt).',
				title: 'Linguist',
			},
			{
				title: 'Leading Presence',
				description:
					'(Rank 1) While you can see and hear each other, allies in short distance of you gain the following effects:\n- You gain +1 boon on your Initiative roll.\n- You gain +1 boon on Spirit rolls against being frightened or losing morale.',
				id: 'b2860b20-caf4-4c15-9301-2c2e43c0fa7e',
			},
			{
				id: '026b6cff-e36a-48b4-aa96-45ae383da4a7',
				title: 'Arcane Awakening',
				description:
					'You have a natural talent for the arcane arts. If you have learned Arcana, you gain +2 Focus. You can cast arcane spells without a spellcasting anchor, but suffer +1 bane on the roll.',
			},
			{
				id: '0e5df849-5c21-48ba-859e-a60a45b5d714',
				description:
					'Re-roll the result of one test and take the new result. You can use this ability once per day.',
				title: 'Will of Perseverance',
			},
		],
	},
	spells: {
		specialization: 'Conjuration, Illusion',
		spells: [
			{
				rank: 0,
				id: '50db0c51-ad0a-4bf9-9ad9-7c331b71ba94',
				properties: '',
				range: 'medium',
				name: 'Arcane Missiles',
				cost: 0,
				target: '8',
				damage: {
					other: 0,
					weapon: 0,
					otherWeak: 2,
					otherCritical: 2,
					otherStrong: 2,
					base: 'MND',
					type: 'blast',
				},
				effect:
					'Conjure one or multiple small projectiles or pure arcane energy and lunge them against a number of creatures.\nWeak. You fire one missile.\nStrong. You fire two missiles.\nCritical. You fire three missiles.\nChoose any number of creatures in range as targets to divide the missiles between. Each missile automatically hits, counting as a weak success, and deals +2 blast damage.',
			},
			{
				name: 'Extraplanar Pocket',
				damage: {
					other: 0,
					weapon: 0,
					otherStrong: 0,
					otherCritical: 0,
					base: 0,
					otherWeak: 0,
					type: 'physical',
				},
				rank: 0,
				cost: 0,
				id: '23f21f7a-7209-42eb-9cc1-ac59f010b390',
				target: '8',
				range: 'touch',
				properties: 'quick',
				effect:
					'Choose one item taking up 1 load or less and hold it out before you. Cast this spell on your turn.\nOn a success, your hand reaches into an extraplanar pocket, either storing the item you are holding or withdrawing an item you stored beforehand from it during your turn.\n\nYou can only ever store items with a combined load of up to 2 + Arcana in the extraplanar pocket. When storing supply in it, you can‘t store more than a d12 (or 5 units) for any single type of supply in it.\n\nOnce you are unconcious, any stored item re-appears before you.',
			},
			{
				id: '0b2d35ba-c83d-43a5-b6ae-40f17315fac3',
				cost: 2,
				rank: 1,
				target: '8',
				range: 'medium',
				properties: 'concentrate, illusory',
				damage: {
					other: 0,
					base: 0,
					type: 'physical',
					otherCritical: 0,
					otherStrong: 0,
					otherWeak: 0,
					weapon: 0,
				},
				effect:
					'You can create a stationary image of a creature or object. Choose a small or medium sized form for your mirage. On a success, your chosen mirage appears. It lasts a short duration or until you move out of range of it.',
				name: 'Mirage',
			},
			{
				properties: 'enchant (*), singular',
				id: '24bca902-2c5a-4467-bba6-799b719a8dc9',
				rank: 1,
				name: 'Infuse Item',
				target: '8',
				cost: 2,
				effect:
					'You touch any medium or smaller item, temporarily infusing it with arcane energy.\nOn a success, the item increases it’s Durability die by one step. If it is a weapon, it deals +1 weapon damage. If it is an armor, shield, or helmet, it grants +1 AV.\nThese effects last for a long duration. This spell counts as an enchantment for a weapon, armor, shield, helmet, or other item depending on which type of item you infused.',
				damage: {
					other: 0,
					otherWeak: 0,
					otherStrong: 0,
					type: 'physical',
					otherCritical: 0,
					base: 0,
					weapon: 0,
				},
				range: 'touch',
			},
			{
				rank: 1,
				range: 'self',
				target: '8',
				effect:
					'You transform your image through illusions, appearing as another similar sized creature.\nOn a success, choose any humanoid form with the same size as yourself. You can also choose any style of clothing or other worn items as part of this spell.\nYou assume your chosen form through illusion. Any parts that appear larger or smaller than your original form aren‘t solid and will be translucent when in contact with other solid matter.\nThis spell lasts for a medium duration.',
				name: 'Disguise Form',
				properties: 'concentrate, illusory',
				cost: 2,
				damage: {
					other: 0,
					otherCritical: 0,
					weapon: 0,
					base: 0,
					otherWeak: 0,
					type: 'physical',
					otherStrong: 0,
				},
				id: 'b0ad95b2-52a0-406b-a043-e389404667e6',
			},
		],
		magicSkill: 'Arcana',
		focus: {
			total: 10,
			current: 8,
		},
	},
	personal: {
		contacts: [
			{
				description: '',
				id: 'e6ef00db-50df-4780-9662-1590037802a6',
			},
		],
		upbringing: 'Academic',
		weight: '',
		allies: [
			{
				description: '',
				id: '81414d51-4638-47bb-a6ce-e2c31b5792ec',
			},
			{
				description: '',
				id: '7816ad3b-3ad6-47b6-9d53-9884ad5fcd6a',
			},
			{
				description: '',
				id: '35aa24ea-527c-42d4-830b-bcd0ebcf6730',
			},
		],
		folk: 'Human',
		age: '',
		motivation: '',
		notes: '',
		height: '',
		rivals: [
			{
				description: '',
				id: '723a8648-dcaf-4af5-89d7-23c5b2f11499',
			},
			{
				description: '',
				id: '7ccd78ee-7271-4b53-9b17-c161b4b2b05a',
			},
			{
				id: 'ff9826fd-3e5a-4810-adee-22f895359cd3',
				description: '',
			},
		],
		background: 'Magus',
		description: '',
		name: 'Sorcerer',
	},
	statistics: {
		strength: {
			wounded: true,
			value: 4,
		},
		resist: 8,
		agility: {
			value: 6,
			wounded: false,
		},
		spirit: {
			value: 6,
			wounded: false,
		},
		resolve: 1,
		health: {
			woundTwo: {
				injury: false,
				fatigueTwo: true,
				fatigueOne: false,
			},
			total: 16,
			woundThree: {
				fatigueOne: true,
				injury: false,
				fatigueTwo: true,
			},
			temp: 0,
			current: 16,
			woundOne: {
				fatigueTwo: false,
				fatigueOne: false,
				injury: true,
			},
		},
		mind: {
			value: 8,
			wounded: false,
		},
		av: {
			other: 0,
			helmet: 0,
			shield: 0,
			armor: 2,
		},
		parry: 7,
		dodge: 8,
	},
	items: {
		items: [
			{
				id: '2c964a68-8b0a-44ad-a590-bf166f2a004f',
				container: 'worn',
				properties: '+2 AV',
				load: 1,
				name: 'Leather Armor',
				amount: 1,
				description: '',
				slot: 'body',
				cost: 50,
			},
			{
				name: 'Gaming Set',
				load: 1,
				cost: 50,
				amount: 1,
				properties: '',
				id: '171778a6-4ae8-416f-935e-a6e0d4db6e4e',
				container: 'backpack',
			},
			{
				name: 'Arcane Conduit',
				properties: '',
				cost: 100,
				amount: 1,
				container: 'backpack',
				load: 0,
				id: '285f440f-719b-4abb-8284-8ff110cd8034',
			},
			{
				amount: 1,
				properties: '',
				container: 'backpack',
				cost: 10,
				id: '6983293b-390e-46ce-9acd-65fffba4c9ea',
				name: 'rations (d6)',
				load: 1,
			},
			{
				cost: 10,
				properties: '',
				container: 'backpack',
				id: 'e1fdb399-c2b4-4370-8403-934b89da1340',
				load: 1,
				name: 'torches (d6)',
				amount: 1,
			},
			{
				load: 1,
				name: 'camping kit',
				amount: 1,
				id: 'ab3dc576-e346-4f9c-83f5-f3a6469ee70e',
				properties: 'provides shelter for a night‘s rest for up to two people',
				cost: 50,
				container: 'backpack',
			},
			{
				load: 1,
				container: 'backpack',
				id: 'c3795c97-8982-499d-8a4f-5a6c79469421',
				name: 'hemp rope',
				amount: 1,
				properties: 'covers a medium distance',
				cost: 10,
			},
			{
				load: 0,
				id: '95e2286e-bbb2-4e1c-9e21-15fd1bf1fa7e',
				amount: 1,
				cost: 50,
				name: 'traveler’s clothes',
				container: 'backpack',
				properties: '',
			},
			{
				id: '9ac37015-a97b-4f5d-8160-002d31fff921',
				container: 'backpack',
				properties: 'holds 2 load',
				name: 'pouch',
				cost: 1,
				load: 0,
				amount: 2,
			},
			{
				load: 1,
				properties: 'holds 10 load',
				cost: 10,
				id: '3f088c11-4b30-4b2f-8272-b0a12f3fa83f',
				name: 'backpack',
				container: 'backpack',
				amount: 1,
			},
		],
		weapons: [
			{
				load: 1,
				name: 'Scepter',
				id: '108895ba-accd-405d-bdf2-541b63a93915',
				damage: {
					other: 0,
					type: 'physical',
					otherStrong: 0,
					otherWeak: 0,
					weapon: 3,
					base: 'STR',
					otherCritical: 0,
				},
				cost: 200,
				properties: 'crush, reach, versatile (+1)',
			},
			{
				description: '',
				properties: 'agile, light, pierce',
				id: 'aec1b755-6eed-4ebb-bea1-e8f2cf7368fa',
				cost: 0,
				damage: {
					other: 0,
					otherStrong: 0,
					otherCritical: 0,
					weapon: 2,
					otherWeak: 0,
					base: 'AGI',
					type: 'physical',
				},
				load: 0,
				name: 'Dagger',
			},
		],
		equipment: {
			hands: {
				name: '',
				cost: 0,
				load: 0,
				properties: '',
			},
			feet: {
				properties: '',
				name: '',
				cost: 0,
				load: 0,
			},
			body: {
				name: 'Leather Armor',
				properties: '+2 AV',
				load: 1,
				cost: 50,
			},
			head: {
				name: '',
				load: 0,
				properties: '',
				cost: 0,
			},
			rings: [
				{
					name: '',
					load: 0,
					properties: '',
					cost: 0,
				},
				{
					name: '',
					cost: 0,
					load: 0,
					properties: '',
				},
				{
					load: 0,
					name: '',
					properties: '',
					cost: 0,
				},
			],
			back: {
				properties: '',
				name: '',
				cost: 0,
				load: 0,
			},
			waist: {
				cost: 0,
				load: 0,
				name: '',
				properties: '',
			},
			neck: {
				name: '',
				properties: '',
				cost: 0,
				load: 0,
			},
		},
		coins: 10,
		encumbrance: {
			currentLoad: 8,
			overencumberedAt: 12,
			encumberedAt: 10,
		},
	},
})
