// list of keywords in this structure: [ "foo": { title: "foo", link: "/docs/foo" } ]

export const keywords: Record<string, string> = {
  // Basic Rules
  "Difficulty": "/docs/basic-rules/how-to-roll#skill-tests",
  "TN": "/docs/basic-rules/how-to-roll#skill-tests",
  "SL": "/docs/basic-rules/how-to-roll#success-levels",
  "Blunder": "/docs/basic-rules/how-to-roll#success-levels",
  "Failure": "/docs/basic-rules/how-to-roll#success-levels",
  "Weak": "/docs/basic-rules/how-to-roll#success-levels",
  "Strong": "/docs/basic-rules/how-to-roll#success-levels",
  "Critical": "/docs/basic-rules/how-to-roll#success-levels",
  "boon": "/docs/basic-rules/how-to-roll#boons-and-banes",
  "boons": "/docs/basic-rules/how-to-roll#boons-and-banes",
  "bane": "/docs/basic-rules/how-to-roll#boons-and-banes",
  "banes": "/docs/basic-rules/how-to-roll#boons-and-banes",
  "roll": "/docs/basic-rules/how-to-roll#skill-tests",
  "test": "/docs/basic-rules/how-to-roll#skill-tests",
  "re-roll": "/docs/basic-rules/how-to-roll#re-rolling-tests",
  "re-rolling": "/docs/basic-rules/how-to-roll#re-rolling-tests",
  "XP": "/docs/basic-rules/character-progression#experience-points-xp",
  "rank": "/docs/basic-rules/character-progression#skill-ranks",
  "Rank": "/docs/basic-rules/character-progression#skill-ranks",
  "level": "/docs/basic-rules/character-progression#character-level",
  "Level": "/docs/basic-rules/character-progression#character-level",

  // Adventurers
  "Language": "/docs/adventurers/languages",
  "Languages": "/docs/adventurers/languages",
  "language": "/docs/adventurers/languages",
  "languages": "/docs/adventurers/languages",

  // Statistics
  "Attribute": "/docs/statistics/attributes",
  "Attributes": "/docs/statistics/attributes",
  "attribute": "/docs/statistics/attributes",
  "attributes": "/docs/statistics/attributes",
  "Strength": "/docs/statistics/attributes",
  "STR": "/docs/statistics/attributes",
  "Agility": "/docs/statistics/attributes",
  "AGI": "/docs/statistics/attributes",
  "Spirit": "/docs/statistics/attributes",
  "SPI": "/docs/statistics/attributes",
  "Mind": "/docs/statistics/attributes",
  "MND": "/docs/statistics/attributes",
  "HP": "/docs/statistics/hit-points-wounds#hit-points-hp",
  "Wound": "/docs/statistics/hit-points-wounds#wounds",
  "Wounds": "/docs/statistics/hit-points-wounds#wounds",
  "Injury": "/docs/statistics/hit-points-wounds#injuries",
  "Injuries": "/docs/statistics/hit-points-wounds#injuries",
  "Fatigue": "/docs/statistics/hit-points-wounds#fatigue",
  "dying": "/docs/statistics/hit-points-wounds#dying",
  "Defense": "/docs/statistics/defenses",
  "Defenses": "/docs/statistics/defenses",
  "Parry": "/docs/statistics/defenses",
  "Dodge": "/docs/statistics/defenses",
  "Resist": "/docs/statistics/defenses",
  "Resolve": "/docs/statistics/resolve",
  "skill": "/docs/statistics/skills",
  "Skill": "/docs/statistics/skills",
  "skills": "/docs/statistics/skills",
  "Skills": "/docs/statistics/skills",
  "Athletics": "/docs/statistics/skills#list-of-skills",
  "Fortitude": "/docs/statistics/skills#list-of-skills",
  "Influence": "/docs/statistics/skills#list-of-skills",
  "Insight": "/docs/statistics/skills#list-of-skills",
  "Perception": "/docs/statistics/skills#list-of-skills",
  "Stealth": "/docs/statistics/skills#list-of-skills",
  "Crafting": "/docs/statistics/skills#list-of-skills",
  "Education": "/docs/statistics/skills#list-of-skills",
  "Lore": "/docs/statistics/skills#list-of-skills",
  "Nature": "/docs/statistics/skills#list-of-skills",
  "Streetwise": "/docs/statistics/skills#list-of-skills",
  "Survival": "/docs/statistics/skills#list-of-skills",
  "Archery": "/docs/statistics/skills#list-of-skills",
  "Fighting": "/docs/statistics/skills#list-of-skills",
  "Arcana": "/docs/statistics/skills#list-of-skills",
  "Mysticism": "/docs/statistics/skills#list-of-skills",

  // Equipment
  "Supply": "/docs/equipment/items-equipment-encumbrance#supply",
  "load": "/docs/equipment/items-equipment-encumbrance#item-load",
  "Load": "/docs/equipment/items-equipment-encumbrance#item-load",
  "agile": "/docs/equipment/armor-weapon-properties",
  "ammo": "/docs/equipment/armor-weapon-properties",
  "blowpipe": "/docs/equipment/armor-weapon-properties",
  "bundle": "/docs/equipment/armor-weapon-properties",
  "covering": "/docs/equipment/armor-weapon-properties",
  "damaged": "/docs/equipment/armor-weapon-properties",
  "double-sided": "/docs/equipment/armor-weapon-properties",
  "entangle": "/docs/equipment/armor-weapon-properties",
  "fragile": "/docs/equipment/armor-weapon-properties",
  "heavy": "/docs/equipment/armor-weapon-properties",
  "light": "/docs/equipment/armor-weapon-properties",
  "narrowed": "/docs/equipment/armor-weapon-properties",
  "noisy": "/docs/equipment/armor-weapon-properties",
  "parry": "/docs/equipment/armor-weapon-properties",
  "pierce": "/docs/equipment/armor-weapon-properties",
  "range": "/docs/equipment/armor-weapon-properties",
  "reach": "/docs/equipment/armor-weapon-properties",
  "reload": "/docs/equipment/armor-weapon-properties",
  "rigid": "/docs/equipment/armor-weapon-properties",
  "slash": "/docs/equipment/armor-weapon-properties",
  "switch (crush / slash)": "/docs/equipment/armor-weapon-properties",
  "thrown": "/docs/equipment/armor-weapon-properties",
  "two-handed": "/docs/equipment/armor-weapon-properties",
  "versatile (+1)": "/docs/equipment/armor-weapon-properties",

  // Combat
  "Initiative": "/docs/combat/combat-scenes#initiative",
  "turn": "/docs/combat/combat-scenes#combat-turns",
  "Turn": "/docs/combat/combat-scenes#combat-turns",
  "turns": "/docs/combat/combat-scenes#combat-turns",
  "Turns": "/docs/combat/combat-scenes#combat-turns",
  "Action": "/docs/combat/combat-scenes#actions",
  "Actions": "/docs/combat/combat-scenes#actions",
  "Quick Action": "/docs/combat/combat-scenes#quick-actions",
  "Quick Actions": "/docs/combat/combat-scenes#quick-actions",
  "Attack": "/docs/combat/combat-scenes#combat-turns",
  "attack": "/docs/combat/combat-scenes#combat-turns",
  "attacks": "/docs/combat/combat-scenes#combat-turns",
  "Attacks": "/docs/combat/combat-scenes#combat-turns",
  "Cast": "/docs/combat/combat-scenes#combat-turns",
  "cast": "/docs/combat/combat-scenes#combat-turns",
  "Dash": "/docs/combat/combat-scenes#combat-turns",
  "dash": "/docs/combat/combat-scenes#combat-turns",
  "Defend": "/docs/combat/combat-scenes#combat-turns",
  "defend": "/docs/combat/combat-scenes#combat-turns",
  "Disarm": "/docs/combat/combat-scenes#combat-turns",
  "disarm": "/docs/combat/combat-scenes#combat-turns",
  "Grapple": "/docs/combat/combat-scenes#combat-turns",
  "grapple": "/docs/combat/combat-scenes#combat-turns",
  "Retreat": "/docs/combat/combat-scenes#combat-turns",
  "retreat": "/docs/combat/combat-scenes#combat-turns",
  "melee": "/docs/combat/attacking#melee-attacks",
  "Melee": "/docs/combat/attacking#melee-attacks",
  "unarmed": "/docs/combat/attacking#unarmed-attacks",
  "Unarmed": "/docs/combat/attacking#unarmed-attacks",
  "ranged": "/docs/combat/attacking#ranged-attacks",
  "Ranged": "/docs/combat/attacking#ranged-attacks",
  "cover": "/docs/combat/attacking#cover",
  "Cover": "/docs/combat/attacking#cover",
  "damage": "/docs/combat/attacking#damage",
  "lasting": "/docs/combat/attacking#lasting-damage",
  "acid": "/docs/combat/attacking#damage-types",
  "blast": "/docs/combat/attacking#damage-types",
  "fire": "/docs/combat/attacking#damage-types",
  "frost": "/docs/combat/attacking#damage-types",
  "lightning": "/docs/combat/attacking#damage-types",
  "necrotic": "/docs/combat/attacking#damage-types",
  "psychic": "/docs/combat/attacking#damage-types",
  "physical": "/docs/combat/attacking#damage-types",
  "poison": "/docs/combat/attacking#damage-types",
  "radiant": "/docs/combat/attacking#damage-types",
  "resistance": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "Resistance": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "resistances": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "Resistances": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "weakness": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "Weakness": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "weaknesses": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "Weaknesses": "/docs/combat/attacking#resistances-or-weaknesses-to-damage-types",
  "melee range": "/docs/combat/distances-movement#distances",
  "close range": "/docs/combat/distances-movement#distances",
  "close": "/docs/combat/distances-movement#distances",
  "short range": "/docs/combat/distances-movement#distances",
  "short distance": "/docs/combat/distances-movement#distances",
  "medium range": "/docs/combat/distances-movement#distances",
  "medium distance": "/docs/combat/distances-movement#distances",
  "long range": "/docs/combat/distances-movement#distances",
  "long distance": "/docs/combat/distances-movement#distances",
  "very long range": "/docs/combat/distances-movement#distances",
  "very long distance": "/docs/combat/distances-movement#distances",
  "extreme range": "/docs/combat/distances-movement#distances",
  "extreme distance": "/docs/combat/distances-movement#distances",
  "out of range": "/docs/combat/distances-movement#distances",
  "Movement": "/docs/combat/distances-movement#movement",
  "bleeding": "/docs/combat/conditions",
  "blinded": "/docs/combat/conditions",
  "burning": "/docs/combat/conditions",
  "charmed": "/docs/combat/conditions",
  "confused": "/docs/combat/conditions",
  "dazed": "/docs/combat/conditions",
  "deafened": "/docs/combat/conditions",
  "distracted": "/docs/combat/conditions",
  "famished": "/docs/combat/conditions",
  "frightened": "/docs/combat/conditions",
  "grappled": "/docs/combat/conditions",
  "hidden": "/docs/combat/conditions",
  "marked": "/docs/combat/conditions",
  "paralyzed": "/docs/combat/conditions",
  "poisoned": "/docs/combat/conditions",
  "prone": "/docs/combat/conditions",
  "pushed": "/docs/combat/conditions",
  "restrained": "/docs/combat/conditions",
  "silenced": "/docs/combat/conditions",
  "slowed": "/docs/combat/conditions",
  "staggered": "/docs/combat/conditions",
  "stunned": "/docs/combat/conditions",
  "suffocating": "/docs/combat/conditions",
  "unconscious": "/docs/combat/conditions",

  // Scenes & Time
  "scene": "/docs/scenes/scenes-time-intervals",
  "Scene": "/docs/scenes/scenes-time-intervals",
  "scenes": "/docs/scenes/scenes-time-intervals",
  "Scenes": "/docs/scenes/scenes-time-intervals",
  "briefly": "/docs/scenes/effect-durations#briefly",
  "short duration": "/docs/scenes/effect-durations#short",
  "medium duration": "/docs/scenes/effect-durations#medium",
  "long duration": "/docs/scenes/effect-durations#long",
  "short break": "/docs/scenes/resting#a-short-break",
  "night's rest": "/docs/scenes/resting#a-nights-rest",
  "bad night": "/docs/scenes/resting#a-bad-night",
  "profession": "/docs/scenes/crafting-professions#list-of-professions",
  "professions": "/docs/scenes/crafting-professions#list-of-professions",
  "Profession": "/docs/scenes/crafting-professions#list-of-professions",
  "Professions": "/docs/scenes/crafting-professions#list-of-professions",

  // Magic
  "Focus": "/docs/magic/magic-spells#focus",
  "concentration": "/docs/magic/magic-spells#spell-concentration",
  "Concentration": "/docs/magic/magic-spells#spell-concentration",
  "spell": "/docs/magic/magic-spells#spells",
  "spells": "/docs/magic/magic-spells#spells",
  "Spells": "/docs/magic/magic-spells#spells",
  "Spell": "/docs/magic/magic-spells#spells",
  "heightened": "/docs/magic/magic-spells#heightening-spells",
  "heightening": "/docs/magic/magic-spells#heightening-spells",

  // Creatures
  "Size": "/docs/creatures/creature-rules#size",
  "sized": "/docs/creatures/creature-rules#size",

}
